In [3]:
import numpy as np
x = np.array([1.0, 3. , 2.6, 4.3, 7.7, 5.6])
y = np.array([1. , 2.6, 3., 4. , 7. , 5.6])
for e in x:
    j = np.where(e == y) # a tuple containing arrays with
                        #indexes
    print(j)
    if(j[0].size != 0):
        print(y[j])
else:
    print("All elements are different")

(array([0], dtype=int64),)
[1.]
(array([2], dtype=int64),)
[3.]
(array([1], dtype=int64),)
[2.6]
(array([], dtype=int64),)
(array([], dtype=int64),)
(array([5], dtype=int64),)
[5.6]
All elements are different


In [4]:
np.__version__

'1.23.1'

In [5]:
a=np.array([1,5,8,9])
b=np.array([16,35,18,98])
b=a+1
b[0]=77
a,b


(array([1, 5, 8, 9]), array([77,  6,  9, 10]))

In [8]:
x = np.array([1., -2., 3., 4., -5.])
i = np.where(x < 0)
x.flat[i] = 0
x

array([1., 0., 3., 4., 0.])

In [28]:
r = np.array([0.09,-0.03,-0.04,0.07,0.00,-0.02])
rneg = r.clip(-1, 0)
rneg=rneg[rneg.nonzero()]
rneg

array([-0.03, -0.04, -0.02])

In [30]:
r = np.array([0.09,-0.03,-0.04,0.07,0.00,-0.02])
rneg = r[r < 0] # masking
rpos = r[r >= 0] # masking
rneg,rpos

(array([-0.03, -0.04, -0.02]), array([0.09, 0.07, 0.  ]))

In [35]:
x = np.array([0])
z = np.array([1.])
x = x.repeat(5)
x
#array([0, 0, 0, 0, 0]) # dtype('int64')----output
z = z.repeat(5)
z,x
#array([ 1., 1., 1., 1., 1.]) # dtype('float64')

(array([1., 1., 1., 1., 1.]), array([0, 0, 0, 0, 0]))

In [37]:
>>> a = np.arange(11)
>>> print(a)
#array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
>>> a = np.arange(10) + 1
>>> print(a)
#array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
>>> a = np.arange(0, 11, 2)
>>> print(a)
#array([ 0, 2, 4, 6, 8, 10])
>>> a = np.arange(0, 10, 2) + 1
>>> print(a)
#array([1, 3, 5, 7, 9])

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]
[1 3 5 7 9]
